### ISSUE TITLE
EVSE MODE CANBUS ERROR

### ISSUE THREAD

**Issue by Mustafa19981903** [uhi22/pyPLC#18]
Hello, even though I follow the installation steps separately for Raspberry Pi and Windows, I get such an error. How can I solve this error? Thank you.
![Ekran Alıntısı](https://github.com/uhi22/pyPLC/assets/63786187/cf20d75c-51b5-42c0-b4d9-37ed0cc96932)

**Comment by uhi22** [comment]
Do you plan to use CAN bus on Windows machine? If yes, we need to add a proper interface layer. The currently used socketCAN is linux specific. If you do not want the CAN, just adjust the pyPLC.ini file, set charge_parameter_backend = none instead of ChaDeMo, this removes the CAN dependencies.

**Comment by Mustafa19981903** [comment]
![Ekran Alıntısı](https://github.com/uhi22/pyPLC/assets/63786187/861b2f34-3be1-4223-99b2-bf483d3e7cb4)
![Ekran Alıntısı1](https://github.com/uhi22/pyPLC/assets/63786187/b66f7a77-c6f6-4e0a-b3d8-096e6fd77dcb)

**Comment by Mustafa19981903** [comment]
It came out like this, I bought it, what can I do? My car is Zoe.

**Comment by Mustafa19981903** [comment]
CanBus Error Solved.
