### ISSUE TITLE
PLC MODULE HARDWARE PROBLEM

### ISSUE THREAD

**Issue by Mustafa19981903** [uhi22/pyPLC#22]
I am using the tl-pa4010p module as PLC and I could not establish a connection with the vehicle. Can you recommend a plc module that can work with the software?

**Comment by Mustafa19981903** [comment]
How did you set these values in the software file with the extension pyplchomeplug.py? I will be very pleased if you give me information.
![Uploading pyplchomeplug.PNG…]()

**Comment by Mustafa19981903** [comment]
![pyplchomeplug](https://github.com/uhi22/pyPLC/assets/63786187/3e2d9a5d-79d6-47ab-a677-505e8118bfd5)

**Comment by pamukcu09** [comment]
> TL-pa4010p modülünü PLC olarak kullanıyorum ve araçla bağlantı kuramadım. Yazılımla çalışabilecek bir plc modülü önerebilir misiniz?

@uhi22

**Comment by pamukcu09** [comment]
> I am using the tl-pa4010p module as PLC and I could not establish a connection with the vehicle. Can you recommend a plc module that can work with the software?

@uhi22

**Comment by uhi22** [comment]
The tl-pa4010p which I used are working. To find out what happens it would be helpful that you add a description what you did, what you expect and what you observe. In best case together with an ethernet log, which you can record using wireshark or tcpdump.

**Comment by pamukcu09** [comment]
> ![pyplchomeplug](https://user-images.githubusercontent.com/63786187/284303130-3e2d9a5d-79d6-47ab-a677-505e8118bfd5.PNG)

We just wondering, if we use different plc module do we have to change this parameters? @uhi22

**Comment by uhi22** [comment]
These values come from the "official" qualcom QCA tool on GitHub, and from the public homeplug documents. If you use plc hardware from other than qualcom/atheros maybe they have different requirements.

**Comment by pamukcu09** [comment]
Thank you so much, we are appreciate for your help
