### ISSUE TITLE
Viewing Sent and Received Messages Together in Evse Mode

### ISSUE THREAD

**Issue by Mustafa19981903** [uhi22/pyPLC#26]
Hello;
When Pyplc operates in evse mode, only the message packets sent by the electric vehicle are seen. What can I do to see both the message packets sent by the vehicle and the message packets sent by the charger when I run Pyplc in EVSE mode?

For example;
"supportedAppProtocolReq",
"supportedAppProtocolRes",

**Comment by uhi22** [comment]
But, the supportedAppProtocolReq is a special case which is not supported by the above update, also not by the pcapConverter.py. Would need improvements.

**Comment by Mustafa19981903** [comment]
@uhi22 thank you for the answer. I updated Fsmevse. I received all the messages up to precharge except the Supported App Protocols message.
[log.txt](https://github.com/uhi22/pyPLC/files/14523156/log.txt)

**Comment by Mustafa19981903** [comment]
This process is completed.
