### ISSUE TITLE
Plc Stamp Mini 2

### ISSUE THREAD

**Issue by Mustafa19981903** [uhi22/pyPLC#27]
Hello
Communication with the vehicle was achieved using the PLC module AR7420. Can I communicate with the vehicle using the PLC stamp mini with the same software? What does it take for me to do it?

**Comment by uhi22** [comment]
I never used this. I assume you can integrate the plcstamp as ethernet device in Linux, and then tell pyPLC to use this.

**Comment by uhi22** [comment]
Assuming this is clarified in the meanwhile. Closing.
